# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Configuration.proto

require 'google/protobuf'


descriptor_data = "\n\x13\x43onfiguration.proto\x12\rcommunication\">\n\rConfiguration\x12\x1d\n\x15\x66\x61ult_tolerance_level\x18\x01 \x01(\x05\x12\x0e\n\x06method\x18\x02 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Communication
  Configuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("communication.Configuration").msgclass
end
